version: '3.9'

services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vaudoise_db
      MYSQL_USER: vaudoise_user
      MYSQL_PASSWORD: vaudoise_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vaudoise_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      UPLOAD_LIMIT: 300M
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "9002:80"
    depends_on:
      - mariadb
    networks:
      - vaudoise_net

volumes:
  db_data: {}

networks:
  vaudoise_net:
